# name: Build and Push Docker Image
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v4
#     
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3
#     
#     - name: Login to Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: your-registry.com
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}
#     
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         push: true
#         tags: |
#           your-registry.com/content-on-cue-media:latest
#           your-registry.com/content-on-cue-media:${{ github.sha }}
#         cache-from: type=gha
#         cache-to: type=gha,mode=max
# 
#     - name: Deploy to Coolify
#       if: github.ref == 'refs/heads/main'
#       run: |
#         # Add your Coolify deployment commands here
#         echo "Deploying to Coolify..."
